// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqSrST89BWx_sVfi15F6r3CWfoIMvYNeM',
    appId: '1:151842399616:web:9ec1f04649b58eb76ecd65',
    messagingSenderId: '151842399616',
    projectId: 'emergency-response-86319',
    authDomain: 'emergency-response-86319.firebaseapp.com',
    databaseURL: 'https://emergency-response-86319-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-response-86319.firebasestorage.app',
    measurementId: 'G-DPJNM1FS1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS8845RjQsdfHqDb8Toy70YpCP_hCLxRM',
    appId: '1:151842399616:android:5b8596ce4e7351276ecd65',
    messagingSenderId: '151842399616',
    projectId: 'emergency-response-86319',
    databaseURL: 'https://emergency-response-86319-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-response-86319.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqSrST89BWx_sVfi15F6r3CWfoIMvYNeM',
    appId: '1:151842399616:web:9498c7e4f69c29a06ecd65',
    messagingSenderId: '151842399616',
    projectId: 'emergency-response-86319',
    authDomain: 'emergency-response-86319.firebaseapp.com',
    databaseURL: 'https://emergency-response-86319-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-response-86319.firebasestorage.app',
    measurementId: 'G-PN5H4NYWCE',
  );

}